files:
  include:
    - './**/*.s+(a|c)ss'
  ignore:
    - './node_modules/**'
rules:
  attribute-quotes:
    - 2
    -
      include: true
  bem-depth:
    - 2
    -
      max-depth: 1
  border-zero:
    - 2
    -
      convention: none
  brace-style:
    - 2
    -
      style: 1tbs
      allow-single-line: false
  class-name-format:
    - 2
    -
      convention: hyphenatedbem
      allow-leading-underscore: true
  clean-import-paths:
    - 2
    -
      leading-underscore: false
      filename-extension: false
  declarations-before-nesting: 2
  empty-args:
    - 2
    -
      include: true
  empty-line-between-blocks:
    - 2
    -
      include: true
      allow-single-line-rulesets: false
  extends-before-declarations: 2
  final-newline:
    - 2
    -
      include: true
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2
  function-name-format:
    - 2
    -
      convention: camelcase
      allow-leading-underscore: true
  hex-length:
    - 2
    -
      style: short
  hex-notation:
    - 2
    -
      style: lowercase
  id-name-format: 0
  indentation:
    - 2
    -
      size: tab
  leading-zero:
    - 2
    -
      include: false
  max-file-line-count:
    - 2
    -
      length: 500
  max-line-length:
    - 2
    -
      length: 120
  mixin-name-format:
    - 2
    -
      convention: camelcase
      allow-leading-underscore: true
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq
        - media
        - clearfix
  nesting-depth:
    - 2
    -
      max-depth: 5
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-ids: 2
  no-qualifying-elements:
    - 2
    -
      allow-element-with-attribute: true
  quotes:
    - 2
    -
      style: single
  variable-name-format:
    - 2
    -
      convention: camelcase
