files:
  include:
    - './**/*.s+(a|c)ss'
  ignore:
    - './node_modules/**'
rules:
  attribute-quotes:
    - 2
    -
      include: true
  bem-depth:
    - 2
    -
      max-depth: 1
  border-zero:
    - 2
    -
      convention: none
  brace-style:
    - 2
    -
      style: 1tbs
      allow-single-line: false
  class-name-format:
    - 2
    -
      convention: hyphenatedbem
  force-attribute-nesting: 2
  indentation:
    - 2
    -
      size: tab
  no-ids: 2
  no-qualifying-elements:
    - 2
    -
      allow-element-with-attribute: true
  quotes:
    - 2
    -
      style: single
