options:
  formatter: stylish
  verbose: true
files:
  include:
    - './**/*.s+(a|c)ss'
  ignore:
    - './node_modules/**'
rules:
  attribute-quotes:
    - 2
    -
      include: true
  bem-depth:
    - 2
    -
      max-depth: 1
  border-zero:
    - 2
    -
      convention: none
  brace-style:
    - 2
    -
      style: 1tbs
      allow-single-line: false
  class-name-format:
    - 2
    -
      convention: hyphenatedbem
      allow-leading-underscore: true
  clean-import-paths:
    - 2
    -
      leading-underscore: false
      filename-extension: false
  declarations-before-nesting: 2
  empty-args:
    - 2
    -
      include: true
  empty-line-between-blocks:
    - 2
    -
      include: true
      allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    -
      include: true
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    -
      convention: hyphenatedlowercase
      allow-leading-underscore: true
  hex-length: 0
  hex-notation: 0
  id-name-format: 0
  indentation:
    - 2
    -
      size: tab
  leading-zero: 0
  max-file-line-count:
    - 2
    -
      length: 500
  max-line-length: 0
  mixin-name-format:
    - 2
    -
      convention: hyphenatedlowercase
      allow-leading-underscore: true
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq
        - media
        - clearfix
  nesting-depth:
    - 2
    -
      max-depth: 5
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals:
    - 0
    -
      allow-map-identifiers: true
      allow-rgba: true
      allow-variable-identifiers: true
  no-combinators: 0
  no-css-comments: 2
  no-debug: 2
  no-disallowed-properties:
    - 2
    -
      properties:
        - zoom
        - '@document'
  no-duplicate-properties:
    - 2
    -
      exclude:
        - display
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    -
      allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: false
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 2
  no-url-domains: 2
  no-url-protocols: 0
  no-vendor-prefixes:
    - 2
    -
      additional-identifiers:
        - khtml
        - o
      excluded-identifiers:
        - webkit
      ignore-non-standard: true
  no-warn: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 0
  placeholder-name-format:
    - 2
    -
      convention: hyphenatedlowercase
      allow-leading-underscore: true
  property-sort-order: 0
  property-units:
    - 2
    -
      global:
        - em
        - rem
        - px
        - '%'
        - ms
        - s
        - deg
        - grad
        - rad
        - turn
        - vw
        - vh
        - vmax
        - vmin
        - dpi
        - fr
  pseudo-element: 2
  quotes: 0
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-bang: 2
  space-after-colon:
    - 2
    -
      include: true
  space-after-comma:
    - 2
    -
      include: true
  space-around-operator:
    - 2
    -
      include: true
  space-before-bang:
    - 2
    -
      include: true
  space-before-colon:
    - 2
    -
      include: false
  space-before-brace:
    - 2
    -
      include: true
  space-between-parens:
    - 2
    -
      include: false
  trailing-semicolon:
    - 2
    -
      include: true
  url-quotes: 0
  variable-for-property: 2
  zero-unit:
    - 2
    -
      include: false
  variable-name-format:
    - 2
    -
      convention: hyphenatedlowercase
